### ISSUE TITLE
Create an automated build system

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#1]
Should be as easy as running a single command (from command line or from Travis (eg)) to create images for any number of targets (ODroid, Khadas VIM, x86 live USB, &c.)

Technologies currently being used:

- qemu
- libvirt
- kitchen

**Comment by mgax** [comment]
So far, we have kitchen working on x86_64 and arm64. It can spin up an ubuntu cloud image, log into it, run commands, and tear it down cleanly.

https://github.com/liquidinvestigations/buildbot

**Comment by mgax** [comment]
I've refactored the buildbot scripts to support arm64 in a sane way.

Also, the [odroid image build script](https://github.com/liquidinvestigations/buildbot/blob/42be8b8/shared/scripts/build_odroid_image.sh) is now in the repo, in the shared folder, so it's visible from within a buildbot VM. Run it like so:

```
kitchen create vm-arm64
kitchen exec vm-arm64 -c "sudo /mnt/shared/scripts/build_odroid_image.sh"
kitchen destroy vm-arm64
```

If all goes well, the liqud image will be saved to `shared/output/odroid-c2-liquid.img.xz`. As far as I can tell, the final image doesn't currently **boot** on the odroid, so we need to debug that.

**Comment by gabriel-v** [comment]
Here's how to create a vagrant .box from a VirtualBox .ova image: [the link](https://github.com/crohr/ebarnouflant/issues/7).

We might want to create a [base box](https://www.vagrantup.com/docs/virtualbox/boxes.html) from scratch, as a separate

**Comment by mgax** [comment]
I've simplified the kitchen commands, it's now a one-liner:

```bash
$ bin/build shared/scripts/build_odroid_image.sh
```

The build now works for odroid-c2, tested by copying to SD card and booting. It previously failed because it was using a broken base image.

Closing the issue; we still need a x86_64 buildbot but that's tracked in #13.
