### ISSUE TITLE
MK/Pit - Tech documentation

### ISSUE THREAD

**Issue by Luthieneye** [liquidinvestigations/liquidinvestigations#10]
Architecture Document, Github

**Comment by alsegno** [comment]
@Luthieneye is this to finalize the architecture document?

**Comment by Luthieneye** [comment]
Yes

**Comment by alsegno** [comment]
Preparation of document outlines to guide investigation into:

1 - HTTPS solutions
2 - Other classes of boards (better than ARM)
3 - 'cloud'/darknet storage options

have been produced and delivered to MK/Pit.

**Comment by alsegno** [comment]
Assigning to @Luthieneye until we can get MK/Pit's details for github.

**Comment by alsegno** [comment]
@Luthieneye I'm leaving this assigned to you in 'ready' state until we decide the best way of handling these.

**Comment by alsegno** [comment]
Closing in favour of #12
