### ISSUE TITLE
Hypothesis error page

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#106]
This is what Hypothesis returns for a `500` error.

<img width="819" alt="screen shot 2017-09-11 at 19 06 05" src="https://user-images.githubusercontent.com/27617/30284789-998366d2-9724-11e7-9630-e2c29a02c44e.png">

**Comment by m-nic** [comment]
@mgax Please find a way to replicate the issue and provide the steps.

**Comment by mgax** [comment]
@m-nic from inside the factory VM, edit the file `/opt/hypothesis/h/h/views/home.py` to insert `raise RuntimeError` at line 26:

<img width="489" alt="screen shot 2017-11-25 at 23 58 42" src="https://user-images.githubusercontent.com/27617/33235267-5e47398c-d23d-11e7-9760-4606d4fb775b.png">

Then run `supervisorctl restart hypothesis-web`. When you navigate to the hypothesis homepage it should return a 500 internal error. The template is at `/opt/hypothesis/h/h/templates/5xx.html.jinja2`.

There's also a 404 page, which you can find at `/aaaaaa` or any random URL, please override that template too (`/opt/hypothesis/h/h/templates/notfound.html.jinja2`).
