### ISSUE TITLE
image compression

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#109]
Currently we compress nightly images with `xz`, which gives a good compression ratio, but it takes a long time. We should benchmark compression time and ratio with a few options:

* `xz`
* `xz -1`
* `gzip`
* `gzip -1`

**Comment by gabriel-v** [comment]
`xz -1` generates a `1.6G` image instead of the `1.3G` for `xz`. I  don't have any other numbers, but I think `-1` is satisfactory.
