### ISSUE TITLE
Run arm64 VMs from the Odroid C2 disk image

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/liquidinvestigations#117]
This is needed to run tests in a VM on the image that resulted from the build process.

**Comment by gabriel-v** [comment]
What this gets us is jenkins-driven tests that run against the nightly C2 image. We do not have these today.

**Comment by gabriel-v** [comment]
Research into getting C2 bios files. If we don't find any, just cut off the bootloader partition.

**Comment by mgax** [comment]
Closing as duplicate of #137.
