### ISSUE TITLE
jenkins domain name & https

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/liquidinvestigations#121]
jenkins.liquiddemo.org?

**Comment by alsegno** [comment]
what does the 'good first issue' label mean? :)

**Comment by gabriel-v** [comment]
well he has to start by doing *something*, right?

**Comment by alsegno** [comment]
:D

**Comment by mgax** [comment]
Yeah I think the label was meant for me. He even assigned the card and moved it to "in progress".

**Comment by mgax** [comment]
There. I configured the names `jenkins` and `*.jenkins`.

```
$ dig +short jenkins.liquiddemo.org
88.99.150.33
```

We should reconfigure the server to listen on port 443, maybe put an nginx reverse proxy in front of tomcat.

**Comment by gabriel-v** [comment]
Thanks guys, done.
