### ISSUE TITLE
End user documentation

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#124]
We need minimal end-user documentation to give to people along with our software. It should answer the following questions:

* [x] how to install from scratch using freshly purchased hardware
* [x] how to do basic configuration of network, users, apps
* [x] how to upload and index data
* [x] how to collaborate (chat, wiki, annotations)

**Comment by gabriel-v** [comment]
User manual is done at https://github.com/liquidinvestigations/docs/tree/master/manual
