### ISSUE TITLE
Rename buildbot to factory

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#125]
Buildbot deserves a cool name and the name shall be `factory`.

* [x] Rename the repo
* [x] Update readme files and scripts
* [x] Update Jenkins

**Comment by alsegno** [comment]
i'm sorry i caught this so late i'd have suggested 'fabrica' or 'atelier'.

**Comment by mgax** [comment]
I've migrated (https://github.com/liquidinvestigations/setup/pull/48) the Jenkins setup from buildbot to the setup repo: https://jenkins.liquiddemo.org/job/liquidinvestigations/job/setup/

Builds are currently failing because the ARM64 worker is not set up.
