### ISSUE TITLE
Find any wifi dongle that works in AP mode

### ISSUE THREAD

**Issue by mrc-toader** [liquidinvestigations/liquidinvestigations#126]
Edimax EW-7811Un / RTL8188cus with hostapd.

**Comment by gabriel-v** [comment]
does not work

**Comment by gabriel-v** [comment]
But tell us why it doesn't work, @mrc-toader
Including some creepypasta from the logs

**Comment by alsegno** [comment]
what about this?

https://askubuntu.com/questions/558893/recommended-usb-wifi-adapter-with-hotsopt-support

Is that in any way helpful?

**Comment by alsegno** [comment]
I know this is focused on the RPi but maybe it's another good starting point? There's a column which says whether the adapter supports AP mode...

https://elinux.org/RPi_USB_Wi-Fi_Adapters#Working_USB_Wi-Fi_Adapters

**Comment by alsegno** [comment]
https://help.ubuntu.com/community/WifiDocs/MasterMode#Purchasing_a_WiFi_adapter

**Comment by gabriel-v** [comment]
Done; see wifi dongles at https://github.com/liquidinvestigations/docs/blob/master/manual/WiFi-Adapters.md
