### ISSUE TITLE
x86 host/x86 guest/x86 image building

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#13]
Use buildbot on x86/x86 to create a raw (USB key) bootable image of liquidinvestigations distribution.

This image should be convertible via qemu-convert (https://docs.openstack.org/image-guide/convert-images.html) to any number of virtualization platforms.

related to #1

**Comment by dreamlayers** [comment]
I'm attempting to adapt build_odroid_image.sh into build_x86_64_image.sh and build an image using ubuntu-16.04-server-cloudimg-amd64-disk1. So far, few changes are needed and later a single script which detects architecture could be used. I'm running into this problem:

```
TASK [hoover : Clone the testdata repo] ****************************************
       fatal: [/mnt/target]: FAILED! => {"changed": false, "cmd": ["/usr/bin/git", "fetch", "--tags", "origin"], "failed": true, "msg": "Failed to download remote objects and refs:  fatal: Not a git repository (or any of the parent directories): .git\n"}
```

The `"cmd"` seems to imply that Ansible didn't understand the parameters and is simply running a default git command. I note that this operation [uses a different format for ansible git parameters](https://github.com/liquidinvestigations/setup/search?utf8=%E2%9C%93&q=git&type=), `repo: ` while others use `repo=`. Though https://docs.ansible.com/ansible/git_module.html says shows the `repo: ` format.

**Comment by dreamlayers** [comment]
It seems the problem with cloning the testdata repo was that it had partially completed, leaving files at the destination which weren't a valid git repository. It probably happened when I ran out of disk space in the image, before enlarging it to 4 gigs. After that, all the Ansible tasks completed successfully.

**Comment by mgax** [comment]
That's great news! Does this mean we have a working x86 image builder?

**Comment by alsegno** [comment]
This was merged on Friday. Need to do a quick test, then we can call it done.

**Comment by mgax** [comment]
I've built an image inside a vmware on my macbook, it took 66 minutes. It's in our [images folder](https://liquidinvestigations.org/images/)/`liquid-20170626-x86_64.img.xz`.

**Comment by alsegno** [comment]
I converted this to a vdi with `qemu-img convert -f raw -O vdi filename.img filename.vdi` and i can't get it to boot. @dreamlayers can you take a look?

**Comment by dreamlayers** [comment]
@alsegno, the VirtualBox boot hang is due to the console= kernel parameter referencing a non-existent device: https://bugs.launchpad.net/cloud-images/+bug/1573095

You can simply remove that parameter from the entry near the end of /boot/grub/menu.lst. This does it automatically from the script https://github.com/dreamlayers/buildbot/commit/3e5bfca7bb6272f8bcaa197cb40673e9f7f12809 (Not sure if I should be committing directly to this repo now.)

**Comment by alsegno** [comment]
@dreamlayers, you can commit directly to the repository, no problem.

I'll look at this tomorrow, try to run it, and verify that it works in virtualbox/vmware, then I think we are close to closing this out.

Do we want to include the --debug/development parameter somewhere that sets up a default user before we close this?

**Comment by dreamlayers** [comment]
Ubuntu cloud-init is causing a delay of a few minutes on startup checking if it's running on a cloud provider. [It can be disabled](https://askubuntu.com/a/579301) though it might be useful for users, so should probably only be disabled on debug builds.

**Comment by alsegno** [comment]
If I understand right, this is because we're specifically using an 'ubuntu cloud' image as our base image. Is that the right base image to use for cases where we just want to run in virtualbox/vmware/qemu on our local boxes?

We should be able to produce cloud-ready images as well as desktop-ready or development-vm ready images, right? Does it make sense to just use a different base image in some cases? make it configurable?

**Comment by mgax** [comment]
> Ubuntu cloud-init is causing a delay of a few minutes on startup checking if it's running on a cloud provider. It can be disabled though it might be useful for users, so should probably only be disabled on debug builds.

I think we should disable it indiscriminately. [Here](https://github.com/liquidinvestigations/buildbot/blob/9a04ff41/prepare_cloud_image.py#L25)'s how it's done in buildbot. We're using the cloud image because it's a convenient ready-made image - we could just as well use debootstrap to create our own.

**Comment by alsegno** [comment]
I still can't boot the image after converting it to vdi and creating a virtualbox VM.

Am I missing something?
https://pastebin.com/5k361bAL

![Screen Shot 2017-06-28 at 20.31.44.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/594119bf3984c3001af93325/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256456fb6b7191a37aef0c2850415b4abe5d4a1f06a3a3dc78e2a436628f550fecd03f5b21c63e14fee9d31fbe02b8298b4f81b3bb9850d2aa6c7bb3d4d216744b470a83ed5e34aa984fc150f04ce04c57a6153463f43b.png)

**Comment by dreamlayers** [comment]
I'm sorry. I can reproduce this also. The cloud image has two grub versions installed: grub-legacy-ec2 and a newer version. I saw that it worked after making a change for the legacy grub and thought it was fixed, but this morning I saw it was getting the console setting from the newer grub. https://github.com/liquidinvestigations/buildbot/commit/b6f0916fddcab4157604dbf8415bc77914e0bc2b should take care of this.

**Comment by alsegno** [comment]
Ok I've tested the vagrant box and it boots just fine (see #images on slack). It looks like we almost have everything complete.

What will it take to close this issue and move on to the next thing?

1 - cron job for nightly/weekly builds?

Should this have its own issue?

**Comment by mgax** [comment]
Yeah, the cron should be a separate issue, with an item that says "document the cron job". That doc should go into an internal wiki that describes our entire ops setup (build machine, website, the ARM boards in the office, future liquid nodes maintained by our team).

But this task is done, let's have closure :beers:

**Comment by alsegno** [comment]
Ok I'll take care of it in the morning.

**Comment by alsegno** [comment]
Ok this task is done & tested. I'm going to create the cronjob issue and assign to boris. This one is closed! Congrats.

**Comment by mgax** [comment]
🍰
