### ISSUE TITLE
odroid c2: auto updates (apt daily activities) to be turned off on images

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#132]
At this stage we shouldn't be auto-updating the OS, it increases boot time and could potentially introduce instability to the system.

**Comment by mrc-toader** [comment]
To be killed with fire.
![22550704_1409368369174402_1937269310_o.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a5502080bf0800129616fe/125516c66e82c728ace21e0d46bac6cf76d2d4f9dbd6ee17f404a3c27115712a7853f77f20d7dc79e6112c5359564dad41370056e0ebc969f9ec6923ce4e01ffd4645b75c76f15f9b8811aed50eb208a4c87bfbc8a48c5ef2f39f5c9de116a415841c3aa1f27aa8b4ac052f74ee14554a3113f6bef73327455d9.jpg)

**Comment by alsegno** [comment]
still?

**Comment by mrc-toader** [comment]
```
systemctl disable apt-daily-upgrade.service
systemctl disable apt-daily.service
systemctl disable apt-daily-upgrade.timer
systemctl disable apt-daily.timer
```

**Comment by gabriel-v** [comment]
I'll put that in ansible, thanks

**Comment by gabriel-v** [comment]
for x86 these are failing:
```
systemctl disable apt-daily-upgrade.service
systemctl disable apt-daily-upgrade.timer
```

**Comment by gabriel-v** [comment]
those two are also failing for the C2

**Comment by gabriel-v** [comment]
we also need to kill `unattended-upgrades`
