### ISSUE TITLE
no admin user in C2 nightly build

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#135]
select * from auth_user in /opt/liquid-core/var/db.sqlite3 returns nothing

**Comment by gabriel-v** [comment]
@alsegno try again with the next image: https://jenkins.liquiddemo.org/job/liquidinvestigations/job/setup/job/master/28/

**Comment by gabriel-v** [comment]
closing in favor of any future issues with the C2 boot
