### ISSUE TITLE
hoover - show the testdata collection even if you're not logged in

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#136]
I'd like to see a demo dataset indexed & searchable from the nightly builds. is this a bad idea?

i'm thinking about it for presentation purposes, mostly, so we don't have an import/index step to go through if we are doing a 'light'/'elevator' demo.

**Comment by germakoci** [comment]
there will be fresh data coming in there, so that can be used actually as an import/index demo; I won't have that data before

**Comment by mgax** [comment]
The testdata dataset is already indexed. We just need to make it visible.

**Comment by mrc-toader** [comment]
Works
