### ISSUE TITLE
ui.liquiddemo.org hangs on 'next'

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#138]
we can't get past the first page of the liquid ui on liquiddemo.org.

after setting the hostname/admin username/password, clicking next hangs forever

**Comment by mgax** [comment]
First problem: the wizard is POSTing at `http://ui.liquiddemo.org/api/registration`. The URL should end with a slash, i.e. `http://ui.liquiddemo.org/api/registration/`.

Second problem, if you try the same thing on liquiddemo.org: the node is already configured, so the wizard is not allowed to save the initial settings.

**Comment by gabriel-v** [comment]
no wizard for leipzig

**Comment by mgax** [comment]
There is no more `ui.liquiddemo.org.` The main liquiddemo has the most recent UI build.
