### ISSUE TITLE
odroid c2 Jenkins build fails

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#139]
https://jenkins.liquiddemo.org/job/liquidinvestigations/job/setup/job/master/30/execution/node/46/log/

cryptography? pypy?! wtf.

**Comment by gabriel-v** [comment]
can't even get that far again. everything is unstable. Will investigate again when we stop rearranging links around.

**Comment by gabriel-v** [comment]
once every 2 days, jenkins produces some useful image.
