### ISSUE TITLE
Support OpenVPN (client/server)

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#14]
The board should support OpenVPN as a client or as a server.

As the deadline approaches this issue will link to use cases.

**Comment by alsegno** [comment]
@dreamlayers Is this something you could help with in the future?

**Comment by alsegno** [comment]
If someone can get #59 resolved then I can start playing with this. I've done openVPN setups before.

**Comment by alsegno** [comment]
This should do it. We will need to include it as a git submodule and work out how to manage the config:

https://github.com/Stouts/Stouts.openvpn

**Comment by alsegno** [comment]
It looks like we have a couple of options here, and they all seem to have their own special problems:

1. use tun only. this (apparently won't work)
2. use tap to bridge networks (this will end up layer 2 bridging both of the networks that we're connecting, and i think that's dangerous)
3. use an mDNS reflector/proxy on either end of the tun connection (some people have run into some problems with this, but it looks like maybe we can configure it in our existing daemon on either end?)

**Comment by alsegno** [comment]
From the avahi-daemon man page. My only concern is the 'ping pong' situation -- we need to be sure that the reflector doesn't identify the tunnel as a 'local interface'

> [reflector]  

> enable-reflector= Takes a boolean value ("yes" or "no"). If set to "yes" avahi-daemon will reflect incoming mDNS requests to all local network interfaces, effectively allowing clients to browse mDNS/DNS-SD services on all networks connected to the gateway. The gateway is somewhat intelligent and should work with all kinds of mDNS traffic, though some functionality is lost (specifically the unicast reply bit, which is used rarely anyway). Make sure to not run multiple reflectors between the same networks, this might cause them to play Ping Pong with mDNS packets. Defaults to "no".
> reflect-ipv= Takes a boolean value ("yes" or "no"). If set to "yes" and enable-reflector is enabled, avahi-daemon will forward mDNS traffic between IPv4 and IPv6, which is usually not recommended. Defaults to "no".

**Comment by alsegno** [comment]
see https://github.com/liquidinvestigations/openvpn-config/

**Comment by alsegno** [comment]
server side does this now from a single script:

https://gist.github.com/alsegno/a112952cf2a93b30ccd1c8a392144bc9

**Comment by Luthieneye** [comment]
Someone recommended https://www.wireguard.com/ as an alternative to OpenVPN. Prlly it's too late now to figure this one out.

**Comment by mgax** [comment]
I'm integrating @alsegno's VPN work into setup. The server setup is done (certificate authority, generating client keys, generating the client config file). Next is loading the client configuration file into another liquid node and connecting to the server.
