### ISSUE TITLE
review aufs/overlay storage for docker

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#141]
Please take a look at this, it shouldn't take long:

https://sthbrx.github.io/blog/2015/10/30/docker-just-stop-using-aufs/

We're running into an issue with aufs kernel support on aarch64 (ubuntu cloud doesn't support it with the 4.4 kernel we're using...)

Any input you have is appreciated.

**Comment by alsegno** [comment]
Aufs is not supported in kernel 4.x

https://askubuntu.com/questions/870889/cant-start-docker-on-ubuntu-16-04-with-driver-not-supported-error/870890

**Comment by gabriel-v** [comment]
moving to backlog, problem only appears in conjunction with your hacks for #137

**Comment by mgax** [comment]
Fun fact – we use kernel 4.4.0 in Factory (I think it's the same kernel you're using) and it does support docker, the version from xenial. Maybe some kernel module is not loaded in your environment.

**Comment by mgax** [comment]
By now we've got Docker out of our system.
