### ISSUE TITLE
First boot error with no app roles installed

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#142]
I'm running a minimal setup with most roles commented out (because hypothesis and hoover and matrix are so bloody huge). First boot ends with the following error (but, interestingly, it thinks it succeeded, because the `first_boot_done` file is there.

```
+ echo 'Running on-boot hook.'
Running on-boot hook.
+ for file in '/opt/common/hooks/on-boot.d/*'
+ '/opt/common/hooks/on-boot.d/*'
./boot.sh: line 33: /opt/common/hooks/on-boot.d/*: No such file or directory
+ echo 'Boot scripts done.'
Boot scripts done.
```

**Comment by gabriel-v** [comment]
1. because i moved the on-boot hooks (that run on each boot) into an +e area. The first boot (initialize.sh) is done.

The actual problem is the bash `for file in *` errors when the dir is empty.

You're going to migrate the first boot logic to python, so closing this.
