### ISSUE TITLE
ubuntu server 16.04 doesn't support WiFi on NUC out of the box

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#144]

**Comment by mrc-toader** [comment]
According to the intel website on this NUC model (NUC7I5BNH), the WiFi Adapter is 8265 and requires the ucode files (not included in ubuntu repos) from this url, which are for kernel 4.6+ but ubuntu 16.04's default is 4.4.
https://wireless.wiki.kernel.org/_media/en/users/drivers/iwlwifi-8265-ucode-22.361476.0.tgz

**Comment by mrc-toader** [comment]
Accidentally clicked Close.

**Comment by gabriel-v** [comment]
Make us a script that installs everything needed. Thanks & have fun

**Comment by mrc-toader** [comment]
Update: the latest version firmware was already there, just requires newer kernel.
I'd suggest getting `linux-generic-hwe-16.04` (4.10.something) because it's in the official xenial repos, when/if @mgax  is willing to reboot the nuc.

**Comment by mgax** [comment]
@mrc-toader I was talking about somebody else's NUC. Closing the issue because it's not clear what should be done. When we need WiFi on our NUC for Liquid Investigations, we'll figure out a solution, document it, and be happy.

**Comment by mrc-toader** [comment]
@mgax updated mentioned kernel, wifi works now
