### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#147]
After running ansible with `devel: true`, creating the liquid user, and rebooting, now any access to http://liquid.local (at the correct ip) gives 'bad gateway.

**Comment by alsegno** [comment]
This seems to be true for all of the different services, ie matrix.liquid.local gives this problem too.

**Comment by alsegno** [comment]
tested from two different machines (me and @mrc-toader )

**Comment by alsegno** [comment]
FYI running `/opt/common/initialize.sh` *appears* to start some things, and runs without error, but we are still getting a 502 when accessing `http://liquid.local`

@mgax or @gabriel-v should provide some support to @mrc-toader so that he can start manual testing on the NUC

**Comment by alsegno** [comment]
NB: systemtl stop/start nginx doesn't have any effect here.

**Comment by alsegno** [comment]
@mrc-toader found a solution. Please document here and close the issue, then continue with manual testing.

**Comment by alsegno** [comment]
@mrc-toader these steps need to be documented in case we need to do this manually at the leipzig demo. 

@mrc-toader Please create a document describing all of the above and put it somewhere.

**Comment by mrc-toader** [comment]
Upon further reading, the official way to start the bundle is running `supervisorctl start all`, can be used with `status` as well.

**Comment by mrc-toader** [comment]
firstboot script is supposed to start them, only on first boot
Must have reboot persistence.
