### ISSUE TITLE
OAuth support for Hypothesis

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#15]
Hypothesis needs to use our OAuth server for authentication

question: who should this be assigned to?

**Comment by alsegno** [comment]
@Luthieneye the Hypothes.is team should be contacted to ensure that this is moving along.

**Comment by Luthieneye** [comment]
FYI, here is the thread between Hypothes.is and Alex re: O auth : https://groups.google.com/a/list.hypothes.is/forum/#!searchin/dev/Third$20party$20accounts/dev/X189Sgj7o40/F0dUVfwoAwAJ

**Comment by alsegno** [comment]
We had a call today -- the plan is for us to meet directly with their development team.

They are currently re-working their authentication mechanism so that it will live in a pop-up. It looks like auth will be handled by a POST which returns a token that can be used by the web app/bookmarklet.

It should be possible to write a small integration that handles their POST, then authenticates to *our* django oauth thing. Maybe some kind of flask thing. After we talk to their people we'll see if this is appropriate.

**Comment by Luthieneye** [comment]
https://github.com/hypothesis/product-backlog/issues/328

**Comment by alsegno** [comment]
@mgax this requires no action from you until they have finished their part. I'm going to keep it in 'in progress' state though so that it receives appropriate attention.

**Comment by mgax** [comment]
I [pinged their mailing list](https://groups.google.com/a/list.hypothes.is/d/msg/dev/X189Sgj7o40/1Ssy3MqREgAJ) a week ago but haven't heard back.

**Comment by mgax** [comment]
Here's an [update from Hypothesis](https://groups.google.com/a/list.hypothes.is/d/msgid/dev/7FE70FDC-1C90-4549-AB25-60BB0669E0C3%40hypothes.is) - they shipped popup login for the client.
