### ISSUE TITLE
catch-all issue for copy/grammar/syntax/spelling

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#150]
There are a number of places that we might want to change the descriptions/copy for stuff in the UI. Let's use this issue so we don't forget to do this.

Will break into smaller issues as needed.

**Comment by alsegno** [comment]
@andreiadam @m-nic please ask us for these if you don't hear from us within the next days.

**Comment by gabriel-v** [comment]
@alsegno as the native english speaker, you should review all text on the ui pages

**Comment by m-nic** [comment]
@alsegno or anyone in the team, could you please provide some raw texts for the pages we have? @alsegno can always review the grammar & spelling.

**Comment by mgax** [comment]
@m-nic just use some lipsum, we can replace it later.

**Comment by alsegno** [comment]
1 - where can I find the latest UI stuff to write copy for?
2 - what's the appropriate method for me to replace the lorem ipsum with something 'real'?

**Comment by alsegno** [comment]
1 - about shouldn't be 'about' in the admin panel on the demo server, it should say 'help'/'contact'
2 - i should write something for this -- @mrc-toader have we got an email alias for support?

**Comment by alsegno** [comment]
about copy: https://workflowy.com/s/B__W.rSUAkRtYcx

@mrc-toader we need a support@liquiddemo.org alias that forwards everything to @mgax's personal email directly.

**Comment by Luthieneye** [comment]
Hey guys, can we remove the Django Admin tab from the  UI. What for do we need it? Also unsure what the 'Reconfigure' tab refers to.

**Comment by Luthieneye** [comment]
Grammar error on Hypothes.is tab:  "If you already installed Hypothesis in your browser, click the button below to start searching THROUGH your annotations" - through spells with H
