### ISSUE TITLE
Admin UI: describe "general status" endpoints on apiary

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#151]
see http://ui.liquiddemo.org/#/admin/status

we just get a literal `{}` as the status.

Is this a problem with the apiary docs or with something else?

**Comment by gabriel-v** [comment]
No problem here. We asked them to print the JSON as it is, because we currently don't know what data will be available on that endpoint. When we will have a definite structure for those endpoints, we will ask them to show the status page instead of the JSON.

**Comment by gabriel-v** [comment]
done; GET `/api/network/status/` describes a list of interfaces with user-friendly display names.
