### ISSUE TITLE
Admin UI: discovery showing unformatted timestamps

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#154]
'Discovery Interface' always shows 'interface_name'.

'Last Seen' always shows 'date in ISO format'.

This is probably an artifact of using the mock server.

**Comment by gabriel-v** [comment]
Artifact of mock server. Will stay as it is until after Leipzig. Moving to backlog.

**Comment by mgax** [comment]
@m-nic the time will come in ISO format that should be parsable by the native JS Date class, e.g. `2017-10-24T11:56:23.711288+00:00`.

@gabriel-v please update the mock data on the liquiddemo.org server to contain valid ISO timestamps.

**Comment by gabriel-v** [comment]
The properly formatted dates are in apiary. Will update the liquiddemo.org server after we've fixed all the other issues with it.
