### ISSUE TITLE
Admin UI: Need to add a 'contact'/'about'  page

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#155]
We need some way of telling people how to contact us in case of problems. Should live under 'Discovery' I guess as 'help' or 'contact' or something sensible

**Comment by alsegno** [comment]
see #28 in liquid-internal repo

**Comment by alsegno** [comment]
@Luthieneye is here in case she wants to add input on the copy for this. if not, just remove yourself andreea

**Comment by mgax** [comment]
@m-nic says:

> that would be a simple page. Does it need to have a simple contact form (if so what is the action we have to apply - is there any API that would manage that?), or is it just some description, with some email, basic info, github page, git issues page?

**Comment by mgax** [comment]
@m-nic it's a simple non-interactive page. We can provide the content via the API as an HTML blob that you can just include in the page.

@gabriel-v does that sound right? And, since you're the API master, can you please spec out an endpoint? We can write a Django template to render the HTML string, and then return it via the API, either wrapped as JSON, or as a text/html body.

**Comment by gabriel-v** [comment]
API for what, contacting a Liquid Node admin through the Admin Panel?
Users can use chat for that.

The idea of the form is to point administrators to us, the creators of the thing.

Don't think it makes sense to be under "Discovery" like Nathan said, but Andrei is the UX expert here.

Make a placeholder page and we will provide the text, links and email addresses.

**Comment by mgax** [comment]
@gabriel-v I was suggesting that we provide the text, links and email addresses via the API. There's nothing dynamic in that content, sure, but it makes it a lot easier for us to fiddle with the content if it's coming from Python code.

Or, if we're confident we can make changes super easily to the UI code, and recompile, then we can just hardcode the content in the UI repo.
