### ISSUE TITLE
Start apps after supervisor started

### ISSUE THREAD

**Issue by mrc-toader** [liquidinvestigations/liquidinvestigations#159]
`supervisorctl status all` reports everything STOPPED

**Comment by mrc-toader** [comment]
From `/opt/common/boot.sh`'s log:
`+ supervisorctl start all
unix:///var/run/supervisor.sock no such file`

It should wait for supervisor to start.

**Comment by gabriel-v** [comment]
should be fixed by https://github.com/liquidinvestigations/setup/commit/c0dbf4cc3dae391e44718548f221d8613adfdd21, will update after checking
