### ISSUE TITLE
UI + API endpoints for OpenVPN

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#160]
This is vital for us to succeed Oct. 31. Super important. Tremendous.

We need another admin panel screen for configuring OpenVPN, and associated API endpoints. 

This will take some work from all parties, but I think we can defer to Oct.31 unless someone wants to scream about getting it for Leipzig.

**Comment by mgax** [comment]
@m-nic says:

> Isn't this a dupe of https://github.com/liquidinvestigations/liquidinvestigations/issues/176? except it would also include API stuff (which doesn't go into our stuff)

**Comment by mgax** [comment]
@m-nic yes, this is a catch-all issue, and we're using it to track the API part of the implementation too. I'll unassign you.

**Comment by mgax** [comment]
Closing since we already have specific issues.
