### ISSUE TITLE
document how to set up a nuc the first time

### ISSUE THREAD

**Issue by mrc-toader** [liquidinvestigations/liquidinvestigations#161]
will update here after creating the file on git

**Comment by mrc-toader** [comment]
I've put it in this gist for now.
https://gist.github.com/mrc-toader/0955f406dd3c514c533055718536d7b0

I should switch it into a markdown file and add it in a repo.
@alsegno , @mgax would it belong here?
https://github.com/liquidinvestigations/docs

**Comment by gabriel-v** [comment]
Yes. @mrc-toader  make a pull request for the docs repo.
