### ISSUE TITLE
Admin UI: change domain via

### ISSUE THREAD

**Issue by Luthieneye** [liquidinvestigations/liquidinvestigations#167]

**Comment by mgax** [comment]
@gabriel-v we need an API endpoint to get/set the domain name.

**Comment by gabriel-v** [comment]
`/api/network/domain/` has been there since the first iteration of the API blueprint

**Comment by mgax** [comment]
@m-nic then the ball is in your court :)

**Comment by m-nic** [comment]
Where do you think this should get placed?

**Comment by mgax** [comment]
I'm thinking a new "general" screen, between "status" and "network". @gabriel-v, @alsegno what do you think?

**Comment by m-nic** [comment]
I was thinking the same, however we need to figure out what is the exact info that would get displayed there.

**Comment by mgax** [comment]
Just the domain for now.

**Comment by m-nic** [comment]
This was done, the Admin UI allows you to change the domain name.
