### ISSUE TITLE
Admin UI: "create user" shows two confirmations instead of one

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/liquidinvestigations#169]
When you create a user with the admin API, and it succeeds, you get two green "Your settings have been updated" confirmations.

I think this happens because we do a "POST /api/users/" and a "POST /api/users/$username/password" one after the other, and the UI shows a confirmation for each.

**Comment by gabriel-v** [comment]
Additionally, I can change the POST `/api/users/` to require a password if this makes more sense.

**Comment by mgax** [comment]
Yeah, I think it makes no sense to create a user without password. The UI has a single step for user creation; the app hooks also expect a password (and we generate a random one as placeholder). Please add it to `POST /api/users/`.

**Comment by m-nic** [comment]
@gabriel-v can you please update Apiary with the new field support?

**Comment by gabriel-v** [comment]
backlog till next Q.

**Comment by mgax** [comment]
@m-nic created separate issue for the API: https://github.com/liquidinvestigations/setup/issues/96

**Comment by mgax** [comment]
@m-nic the API and its docs are updated. I kicked off a [new build](https://jenkins.liquiddemo.org/job/liquidinvestigations/job/setup/job/master/118/).
