### ISSUE TITLE
Admin UI: make the ENTER button work

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/liquidinvestigations#170]
because right now it doesn't

**Comment by mgax** [comment]
@m-nic says:

> This seems to be an issue on OSX Safari (will try fixing it on my Mac)

**Comment by gabriel-v** [comment]
This works on chrome and firefox on our linux machines.
Closing; reopen if found to be important

**Comment by mgax** [comment]
Still doesn't work. By the way, if I press "tab" to get to the "add" button, and *then* press enter, the form submits. But if I press enter while the "last name" field is focused, nothing happens.

**Comment by gabriel-v** [comment]
Enter button also doesn't work as expected on Chrome, on the login screen (/accounts/login).
The enter button only works if one of the input fields (username/password) is focused. If one of those isn't focused, the enter button doesn't work.
