### ISSUE TITLE
Fix demo server

### ISSUE THREAD

**Issue by Luthieneye** [liquidinvestigations/liquidinvestigations#174]

**Comment by Luthieneye** [comment]
According to Gabi the demo server is not working any longer.  For Q3 demo purposes we should get it up and running again.

Here is what we provided Google in Q2 with:
https://liquiddemo.org. 
username: test 
password: y8kBhM5ytqmqgHRz2qJz8/x3EAxcmfeOLG2plpfO

**Comment by gabriel-v** [comment]
@Luthieneye please don't publish passwords in public issues thanks

**Comment by Luthieneye** [comment]
understood

**Comment by mgax** [comment]
Demo server is updated for the Q3 milestone. Any individual bugs deserve individual issues from this point on.
