### ISSUE TITLE
Admin UI: VPN management

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/liquidinvestigations#176]

**Comment by mgax** [comment]
@m-nic says:

> we should have a different section/page for that, maybe something similar to the network section - where you have tabs that allow you to see status and toggle client/server, add & list keys, download, see key details & be able to revoke it. There should also be the possibility to upload a config file.

**Comment by mgax** [comment]
@m-nic yep, that's correct. Can you draw a quick wireframe for that screen, so we make sure we're all on the same page? Thanks!
