### ISSUE TITLE
Prove that network discovery works

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/liquidinvestigations#178]
Both on LAN and over VPN

**Comment by alsegno** [comment]
What does 'discovery' mean in the case where the VPN client is my Mac desktop? Presumably I'm not running zeroconf or any 'mDNS reflector' on my laptop. Does this mean that I can't access 'discovered' nodes if I use my laptop to directly connect to the VPN?

This may relate to an OpenVPN DNS 'push' setting that could get a bit hairy if we don't pay attention to it...

**Comment by mgax** [comment]
Proved.
