### ISSUE TITLE
Sandboxing of privilege escalation

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#18]
We should restrict sudo to specific commands.

**Comment by gabriel-v** [comment]
Right now, the plan is to run `discover` and `systeml` as root.
With additional effort, both services can run as the non-privileged `liquid` user with the following setup:
- the `liquid` user has read/write permissions to `/var/run/supervisor.sock`
- the `liquid` user has read/write access to the `/var/lib/liquid/conf/supervisor/conf.d/*` supervisor configuration files
- everything that is not a daemon and must run as root (e.g. brctl) is listed in `/etc/sudoers`

That way, we use both sudo and supervisor for privilege escalation.

**Comment by mgax** [comment]
I think we should just run them as root. Sudo just makes our life harder which makes it easier to leave security holes.

**Comment by alsegno** [comment]
I will agree with Alex, and also I'd like to close this issue as its scope is poorly defined.
