### ISSUE TITLE
API should always return notification messages in the same format.

### ISSUE THREAD

**Issue by m-nic** [liquidinvestigations/liquidinvestigations#186]
We should have a standard format for any success/error message that comes from the backend API.
Basically my proposal is to always return a dictionary of this kind for all the API responses.
```
{
	"notifications": {
		"error": ["some error"],
		"success": ["successfully updated"],
		"info": ["please reboot"]
	}
}
```

**Comment by mgax** [comment]
That would be a bad separation of concerns. The API's job is to say what went wrong, not what the user should see. The JS admin UI code should parse the API's errors and figure out what user messages make sense.
