### ISSUE TITLE
Always show •••••••• next to the password eye icon

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#192]

**Comment by alsegno** [comment]
I'm not sure what this does. Maybe it's obvious.

![screen shot 2017-10-31 at 01 00 34](https://user-images.githubusercontent.com/3958483/32201378-026a766c-bdd7-11e7-88d3-2c98e929ff89.png)

**Comment by mgax** [comment]
Normally it shows `••••••••`, but the password is blank, so it shows no `•`. I think it should always show 8x`•` regardless of the password.

**Comment by mgax** [comment]
@m-nic does this change make sense? If so, please make it happen :)

**Comment by m-nic** [comment]
This will be done this week.
