### ISSUE TITLE
Display information on Admin's Status Tab

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#193]

**Comment by mgax** [comment]
First we need to provide all the relevant information via the API.

**Comment by Luthieneye** [comment]
We need to decide what the user will see here ( i.e. board status, active services, # of users on the system)

**Comment by gabriel-v** [comment]
@m-nic please move the current content from the Status Tab (the list of interfaces, that currently says "No information") to the Network Status tab, at the bottom of the page.

Then, implement a simple list that displays entries "title" and "text", one on each line. Take the data from `/api/status/`. See https://liquidinvestigations.docs.apiary.io/#reference/admin-panel/general-status/get-general-system-status
