### ISSUE TITLE
demo server: admin panel: vpn: key details 'revoked' should not be an x/check icon, should be yes/no.

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#195]

**Comment by alsegno** [comment]
![screen shot 2017-10-31 at 01 03 54](https://user-images.githubusercontent.com/3958483/32201469-7e7eb5c4-bdd7-11e7-91bf-a93ba34ccbc0.png)

**Comment by mgax** [comment]
@m-nic what's the status on this?

**Comment by m-nic** [comment]
This will be done this week.
