### ISSUE TITLE
dokuwiki inaccessible because of 'HSTS'

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#199]

**Comment by alsegno** [comment]
![screen shot 2017-10-31 at 01 16 59](https://user-images.githubusercontent.com/3958483/32201834-3ddb4864-bdd9-11e7-875a-d7ee4efa5b25.png)

**Comment by gabriel-v** [comment]
it was supplying the wrong certificate because of a typo. fixed in commit on master
