### ISSUE TITLE
Update 'first boot'/'config' scripts

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#2]
To consume configuration file, perform initial box setup.

Includes the following scenarios:

- first boot
- reboot
- migrate

**Comment by alsegno** [comment]
config file should contain:

- hostname, e.g. liquid.example.com
- admin username+password
- wifi client/hotspot, ssid+password

first boot should:

- generate per-application config files that include hostname
- create admin user(s)
- in case of failure (ie missing config file/stick):
  - show error on default nginx page, console
  - report at http://firstbootliquid.local

**Comment by alsegno** [comment]
Sample config files will live here:

https://github.com/liquidinvestigations/liquidinvestigations/tree/master/sample_configs

There's a base config file there that will support @gabriel-v in his work tonight.

**Comment by gabriel-v** [comment]
I've migrated all service configuration from [setup](https://github.com/liquidinvestigations/setup) to [systeml](https://github.com/liquidinvestigations/systeml).

You can see my ongoing work on [the setup branch](https://github.com/liquidinvestigations/setup/tree/rearrange-conf-files) and [the systeml branch](https://github.com/liquidinvestigations/systeml/tree/initial-proposal).

Until we formalize mounting configuration files from block devices, the configuration script is expected to live at `/opt/systeml/systeml/config.yml`.

**Comment by alsegno** [comment]
The milestone requires us to deliver a config file along with an image. How should we instruct our patron to use these two things together?

**Comment by mgax** [comment]
> The milestone requires us to deliver a config file along with an image. How should we instruct our patron to use these two things together?

With #48 that you just de-scoped.

**Comment by alsegno** [comment]
Descoping this as well.

**Comment by alsegno** [comment]
This all lives in #48 now. If I've got this wrong, please let me know and we can reopen/reframe this issue.
