### ISSUE TITLE
Evaluate viability of HackMD on ARM

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#20]

**Comment by alsegno** [comment]
Note: we may want to look at Etherpad here too.

**Comment by alsegno** [comment]
First step: install on x86, keep notes of dependencies &c.

**Comment by alsegno** [comment]
@mrc-toader we have ODroid XU4 boxes - maybe you can take one home to work on it, or do it here? Do you have an estimate of when you could validate the HackMD install on ARM?

**Comment by mrc-toader** [comment]
Ok, I could drop by today or tomorrow evening after work, pick it up and go through the install process on it, since it was pretty straightforward on x86. I could have an answer by monday on it.

**Comment by alsegno** [comment]
Perfect. You'll either need an SD card writer, or to write the base image while you're here.

Find the image here:

http://odroid.com/dokuwiki/doku.php?id=en:xu3_release_linux_ubuntu

For this task you don't need to set up all of liquid, just install that image, install hackmd, and keep notes. From there we can move into dockerizing, &c.

Once you have it working I'd like to take a look at it, so if you get some success maybe bring the board back in.

**Comment by mrc-toader** [comment]
I've had a few dependencies issues with npm, still digging into it; tonight i'm gonna check the versions vs local machine where the install went well.

**Comment by alsegno** [comment]
Ok. But you need to remember that they're different architectures.

**Comment by mrc-toader** [comment]
Captain's log.
Dependency hell broke loose on lacking arm support, hackmd died a horrible death. However, I've successfully installed Etherpad. I'm gonna poke at customizing it's install settings (db to use, default port, preinstalling plugins).

**Comment by alsegno** [comment]
can you create a new issue called 'evaluate etherpad on arm', and use that to track this?

as soon as you do that we can close this one.

**Comment by mrc-toader** [comment]
Well, I'm currently going through the basics of docker, then I'll attempt to build hackmd's docker repo with a few tweaks for arm and see how that goes, at Victor's suggestion, since hackmd is a lot better feature and stability wise.
If it still doesn't work, will make different issue thread and switch it.
Not much to evaluate, etherpad works out of the box on arm.

**Comment by alsegno** [comment]
do you have an update on this?

**Comment by mrc-toader** [comment]
Yes, it works and I made a wiki with the manual build process and deps fixing. I'll start dockerizing it next week.

**Comment by alsegno** [comment]
Can you link to the wiki here?

**Comment by mrc-toader** [comment]
Yes. Here it is. This issue can be closed. We'll talk about the next parts on thursday, when I'll be available full time.
http://sentre.de:6080/grain/D8Dx2H6bf4DWFkMwjhET2a/software/hackmd

**Comment by alsegno** [comment]
Perfect. Next time, feel free to close it yourself. See you Thursday.
