### ISSUE TITLE
davros inaccessible on demo server

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#200]
internal application error?

**Comment by alsegno** [comment]
![screen shot 2017-10-31 at 01 17 57](https://user-images.githubusercontent.com/3958483/32201876-6b1a890c-bdd9-11e7-92dd-8355f467cad8.png)

**Comment by gabriel-v** [comment]
https reverse proxy issues with oauth2, fixed in lastest master branch
