### ISSUE TITLE
Review testing documentation

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#209]
* https://github.com/liquidinvestigations/liquidinvestigations/blob/master/testing/systems_test_plan.md
* http://sentre.de:6080/grain/D8Dx2H6bf4DWFkMwjhET2a/testing/uat

**Comment by mgax** [comment]
@alsegno @Luthieneye looks good to me. I've made a few changes, you can see them in the [git logs](https://github.com/liquidinvestigations/liquidinvestigations/compare/d47629ff...b3ecf22).

**Comment by Luthieneye** [comment]
Test Cases (to  manually test liquid features) - Needs more input
https://docs.google.com/spreadsheets/d/1piUtwiIZTKfNh0dHckIfPob6Nw7AQc6JqQziJogRRAk/edit#gid=2020650119

We still need a document with some basic guidelines for Performance testing 
VPN  (scalability/stress testing)
Hoover Indexing (scalability/stress testing)

**Comment by mgax** [comment]
@gabriel-v and @mrc-toader came up with a manual QA testing script for the cloud image: https://github.com/liquidinvestigations/docs/blob/master/testing/Cloud.md. Next up, we need a similar script for the Odroid C2, I made a dedicated issue for that: https://github.com/liquidinvestigations/liquidinvestigations/issues/251
