### ISSUE TITLE
Disallow changing the domain name after welcome form

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#211]
It makes no sense to change the domain of an already-configured node. And matrix complains loudly when you try: `Found users in database not native to matrix.ghost.example.org! You cannot changed a synapse server_name after it's been configured`

**Comment by gabriel-v** [comment]
remove this endpoint: https://liquidinvestigations.docs.apiary.io/#reference/network-management/domain-configuration/update-network-domain
