### ISSUE TITLE
Show progress in admin UI while reconfiguring

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#230]
There's an endpoint `/api/configure/status/` that returns `status` as `ok`, `reconfiguring` or `broken`. Display the "loading" overlay and poll every 1s to see if the status changes. Also print the `detail` string.

**Comment by m-nic** [comment]
This feature has been enabled for the available services. Are there other API calls that need to trigger the same feature after they are called?

**Comment by gabriel-v** [comment]
All of the `PUT /api/*` or `POST /api/*` endpoints will trigger a reconfiguration, not just the `/api/services` ones. Networking, ssh, vpn, everything. To be save, I'd say all `PUT/POST /api/*` calls should trigger a check if there's a reconfiguration to be done.

**Comment by gabriel-v** [comment]
There are some edge cases to fix, we'll provide details soon

**Comment by gabriel-v** [comment]
1. Please poll the `/api/configure/status/` endpoint at all times, forever, for each tab that renderes the Admin page. This is so all tabs get locked if someone starts a reconfiguring. Trigger a `GET /api/configure/status/` every 1s.
2. Keep going with the poll forever, even if requests start to fail. They will return after the device is reconfigured, after a few minutes. If one request fails to return the `detail` field, keep the last `detail` field.


5.  Render the `dump` field in `<pre>` tags on the spinner.
3.  Please add an 'X' button in the top-right corner of the spinner. If that button is pressed, no other spinner will appear until the user refreshes.
4. When the user presses 'X', they should be able to change settings and press buttons.
5.  All information provied on the spinner (the "detail" field and "Repair" button) should also be present in the page, if the user decides to press 'X'. Put that information in the header. Also, please provide a button that brings back the spinner (so the user can see the `dump` field)



Some problems:

-  sometimes, the `detail` text doesn't show up

**Comment by m-nic** [comment]
When clicking repair this is what happens: the ui calls /api/configure/repair and starts polling /api/configure/status. 
The issue is that the immediate status request would still return broken (that would also get shown in the ui).
Is something that can be easily fixed from backend? 
Also I don't see any dump in the response.

**Comment by gabriel-v** [comment]
We'll investigate it, but the UI should be resilient to such problems (returning the old status for a short time). After that initial incorrect response, the UI should keep polling and display the progress when `/api/reconfigure/status` starts responding with 'reconfiguring'
