### ISSUE TITLE
VPN Server dies cloud-vm

### ISSUE THREAD

**Issue by mrc-toader** [liquidinvestigations/liquidinvestigations#242]
Testcase scenario:

(prior to running cloud vm `sudo socat udp-listen:1194,fork udp:127.0.0.1:1194` )

- turn VPN Server toggle on
- generate Key
- import key in client
- try to connect (fails)
- turn VPN Server toggle off/on
- factory gets killed

These steps made qemu render my host os unusable.

**Comment by gabriel-v** [comment]
Don't use socat to forward a port to itself. We were using it when we were outputting that port to `11194` from factory, but it's not needed anymore.

**Comment by mgax** [comment]
@mrc-toader is this issue still relevant?
