### ISSUE TITLE
matrix not working on odroid c2

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/liquidinvestigations#249]
first boot lasts another 40 minutes

**Comment by gabriel-v** [comment]
![terminaaaaaaaaaala-25675343_1395417240566673_1869170420_n](https://user-images.githubusercontent.com/7493327/34304979-cf59248e-e744-11e7-8254-17ff1a8380fa.jpg)

**Comment by mgax** [comment]
Should work now, @mrc-toader please check.

**Comment by mrc-toader** [comment]
Works.
