### ISSUE TITLE
Update Hypothesis client integration

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#25]
They changed the name of an environment variable: https://groups.google.com/a/list.hypothes.is/forum/#!msg/dev/WndivGDfOxE/hi91QiXkAQAJ

**Comment by alsegno** [comment]
Since this is not so time consuming, can be completed today or tomorrow.

**Comment by mgax** [comment]
Turns out, we're already using `SIDEBAR_APP_URL `: https://github.com/liquidinvestigations/h-client-build/blob/master/bake.py#L17
