### ISSUE TITLE
Manual QA instructions for Odroid C2

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#251]
Adapt the cloud image testing instructions (https://github.com/liquidinvestigations/docs/blob/master/testing/Cloud.md) to the Odroid C2 distribution.

**Comment by mrc-toader** [comment]
Initial testing steps for C2 / Rock64 here:
https://github.com/liquidinvestigations/docs/blob/master/testing/ARM64.md
