### ISSUE TITLE
Odroid DNS stops working

### ISSUE THREAD

**Issue by mrc-toader** [liquidinvestigations/liquidinvestigations#254]
- flashed fresh odroid image
- connected lan cable
- changed admin user and pass in welcome
- connected odroid to wifi network
- liquid.example.org doesn't work anymore
- added odroid's ip and domain to hosts
- works again

**Comment by mgax** [comment]
Maybe this is related to https://github.com/liquidinvestigations/liquidinvestigations/issues/264. Please test in the next build.

**Comment by mrc-toader** [comment]
Works now.
