### ISSUE TITLE
do a manual test of the cloud image of Liquid Investigations

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/liquidinvestigations#255]

**Comment by mrc-toader** [comment]
Tested apps, working ok. Must test data collections uploaded to davros.

**Comment by mgax** [comment]
Blocked on https://github.com/liquidinvestigations/setup/pull/127, https://github.com/liquidinvestigations/setup/pull/128

**Comment by mgax** [comment]
is. done. already.
