### ISSUE TITLE
Davros navigation menu integration

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#258]
The davros UI update was disabled here because of performance issues:
https://github.com/liquidinvestigations/ui-templates/pull/4/commits/ca801f1f714e9632cc725f6250e1759fd5951a20

We should pre-build davros UI with placeholder for URL.

**Comment by mgax** [comment]
addressed by https://github.com/liquidinvestigations/ui-templates/commit/94063fe337ab0d4b4b81a3b9e0ba96418815ea2d, please test in the next build.

**Comment by mrc-toader** [comment]
Works.
