### ISSUE TITLE
Matrix doesn't turn off

### ISSUE THREAD

**Issue by mrc-toader** [liquidinvestigations/liquidinvestigations#262]
From AdminUI > Services toggle.
I killed it gracefully with supervisorctl stop, used around ~1GB ram.

**Comment by mgax** [comment]
The expected behaviour is for ansible to remove matrix from supervisor. I've just tested on an odroid, and it does get removed properly, and no processes are left over in the system.

**Comment by mrc-toader** [comment]
It's horribly slow, but it works.
