### ISSUE TITLE
Some apps don't start on OdroidC2 reboot

### ISSUE THREAD

**Issue by mrc-toader** [liquidinvestigations/liquidinvestigations#264]
` avahi-daemon, davros-authproxy, lan-dnsmasq, liquid-core, liquid-discover `

Had to assign myself a static ip, ssh in, start them, restart nginx.

`/var/log/rc.local.log` gets updated on reboot, says they get started ok.

**Comment by mgax** [comment]
@mrc-toader should be fixed in the next build, please test.

**Comment by mrc-toader** [comment]
Seems to be working now.
