### ISSUE TITLE
Manual test on rock64

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#267]
Please perform a full manual test on rock64, we have almost-working images :)

A workaround for https://github.com/liquidinvestigations/setup/issues/124 is needed: upgrade ansible to version 2.4 *before* submitting the welcome form.

[here](https://jenkins.liquiddemo.org/job/setup-rock64/view/change-requests/job/PR-121/11/) is the image.

**Comment by mrc-toader** [comment]
The generated images work now.
