### ISSUE TITLE
Reconfigure still spins after it finished.

### ISSUE THREAD

**Issue by mrc-toader** [liquidinvestigations/liquidinvestigations#270]
![reconfigure-spin.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a5502080bf0800129616fe/125516c66e82c728ace21e0d46fa91992c8c85a088fcad46e94ee09d27046b313916ac217586f76ae5002e585b5e4ffe450d5f47f9abd87aa6b73f72835c0be9d46a4d68d47f40f2ecdd42e64bef62994597b7bb804dc5e93b24e68c8b4c391b02189bb2.png)

**Comment by mrc-toader** [comment]
![reconfigure-spin.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a5502080bf0800129616fe/125516c66e82c728ace21e0d46fa91992c8c85a088fcad46e94ee09d27046b313916ac217586f76ae5002e585b5e4ffe450d5f47f9abd87aa6b73f72835c0be9d46a4d68d47f40f2ecdd42e64bef62994597b7bb804dc5e93b24e68c8b4e3b1c07109bb2.png)

**Comment by m-nic** [comment]
what are the conditions to replicate the issue. Thanks!

**Comment by mrc-toader** [comment]
I can't seem to replicate it on x86_64 / cloud, it only happens on ARM.
Basically says this (photo) until I refresh and login.
![403.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a5502080bf0800129616fe/125516c66e82c728ace21e0d46bcc4c961cec1b99de6b546a749b2ce6b137e277855a17f75d5b07dbd437a515e5c4ca541585b41fbeb9539e4e76224d50152a7842f4d7ed43c16a6b9871eb903ba26894f80b5b5835e8d.png)

**Comment by m-nic** [comment]
Can you update the ARM with the latest UI and try to replicate the issue? Please close the this issue if no longer present.

**Comment by mrc-toader** [comment]
Works now, thanks.
