### ISSUE TITLE
Wifi client doesn't reconnect after reconfigure/reboot.

### ISSUE THREAD

**Issue by mrc-toader** [liquidinvestigations/liquidinvestigations#271]
AdminUI > Network > Wan
Works only if DHCP toggle is off.

**Comment by mgax** [comment]
That's weird, the DHCP toggle is a no-op. And I've seen the wifi reconnect after reboot. Please re-test and close.

**Comment by mrc-toader** [comment]
With the last builds it worked on my testing too, reconfigure was probably got broken on that image. Closing now. If I notice it again and can replicate it, I'll make a new issue.
