### ISSUE TITLE
Test odroid c2 with only hoover + davros

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#273]
Let's see if the odroid can index some non-trivial data. Disable all non-essential apps, upload the testdata collection, and measure some performance: how long it takes to process testdata, and maximum memory used during the process.

When measuring the time it takes to index, be sure to watch when the actual processing starts - it may take up to one minute before it begins.

Then, browse through the files in hoover, to see if it missed anything, e.g. because of parsing errors, perhaps some external tool is missing from snoop.

**Comment by mrc-toader** [comment]
Also tested with just matrix disabled. Works reasonable but should boot with just the two until the data is digested.
