### ISSUE TITLE
Review Rock64

### ISSUE THREAD

**Issue by Luthieneye** [liquidinvestigations/liquidinvestigations#28]
presentation:
https://www.pine64.org/?page_id=7147 

review: 
http://www.cnx-software.com/2017/06/08/rock64-is-a-rockchip-rk3328-development-board-with-up-to-4gb-ram-4k-hdr-gigabit-ethernet-and-usb-3-0/ 

ARMbian support: https://forum.armbian.com/index.php?/topic/4451-example-support-proposal-for-rock64/

**Comment by alsegno** [comment]
Mircea - is this something that you can do? We have the board in the office right now and we could start playing with it.

As nightly builds are broken, I don't think we're ready to just drop an image onto this box, but maybe starting with a fresh Ubuntu install and running ansible is a good start, to see what's (un)supported out of the box?

When are you around to start looking at stuff like this?

**Comment by mrc-toader** [comment]
Yes, I'll poke at it and see if it works or/how dies. I can come starting tomorrow.

**Comment by alsegno** [comment]
Any progress on this?

**Comment by gabriel-v** [comment]
The rock64 works as a build slave for building C2 images.

**Comment by gabriel-v** [comment]
power jack fits without problems into sound jack. confusing

**Comment by mgax** [comment]
this works:

![img_8688](https://user-images.githubusercontent.com/27617/31091079-72bc5c86-a7b2-11e7-9b52-f600526f0c44.jpg)

this does not:

![img_8689](https://user-images.githubusercontent.com/27617/31091091-76e51118-a7b2-11e7-9c5b-fbb54e67f602.jpg)

**Comment by gabriel-v** [comment]
this looks good in general; we need to produce run a recent nightly image on it

**Comment by mrc-toader** [comment]
A liquid image build for rock64 is in progress: https://github.com/liquidinvestigations/setup/pull/121

**Comment by Luthieneye** [comment]
This could be a great alternative to Odroid if optimization process stalls.

**Comment by mgax** [comment]
We are building full images for rock64 and they work just as well as the odroid c2 image. So, in conclusion, we can use it as our main platform.
