### ISSUE TITLE
Remove validation from admin wifi client 

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#282]
Right now you can't disconnect from a wireless network. Make the ssid+password fields optional so the user can un-set them.

**Comment by mgax** [comment]
Done, please check the next build.

**Comment by mgax** [comment]
Testing depends on https://github.com/liquidinvestigations/setup/issues/132

**Comment by gabriel-v** [comment]
will also need to remove validation for the backend, in liquid-core

**Comment by gabriel-v** [comment]
UI changes are done
