### ISSUE TITLE
ARMbian-debian image

### ISSUE THREAD

**Issue by Luthieneye** [liquidinvestigations/liquidinvestigations#29]
Pros for using of armbian-debian, instead separate images for each type of box:

-Armbian image covers directly +20 different boards and their drivers (runs on odroid as well khadas)

-Very active community (unlike for khadas/odroid)

- Reasons for debian: https://forum.armbian.com/index.php?/topic/4291-armbian-debian-vs-ubuntu-future-versions/#comment-31952

- Easier to extend a better security tool chain, no dependencies for ubuntu-"experiments" (see upstart, unity, snappy format etc)

**Comment by alsegno** [comment]
I'll do some research on this and put together a little paper.

**Comment by alsegno** [comment]
I don't think this needs a paper, or needs to be an open issue. This is basically not the right fit for what we're doing.

Ansible currently works against Ubuntu, which is one of the distros that ARMbian provides. The other that they provide is Debian, and depending on the boxes we want to support, we can make ansible work against that.

It's not a priority right now to target both -- best to build to Ubuntu & the boxes we have now, then modify for Debian later if necessary.
