### ISSUE TITLE
Nightly build crontab on hetzner server

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#33]
* [x] create a cron job that runs nightly to produce all relevant images (ie x86, ARM, raw disk files, vmware/virtualbox images, vagrant boxes) and put them on liquidinvestigations.org/images.
  targets:
    * [x] `x86_64` raw image, xz-compressed
    * [x] vagrant box
    * [x] `arm64` odroid-c2 raw image, xz-compressed

  NOTE: we should probably think about how much space these will take in the long run. how many days history should we keep here?
    * [x] set up [monit](https://mmonit.com/monit/documentation/monit.html) to warn us when the server runs out of disk space

* [x] put this in a gitlab project in sandstorm (we don't need to expose our personal plumbing to the world)

* [x] document this process in the wiki in the abovementioned gitlab instance. audience should be implementers, so can probably be a set of bullet points, nothing too fancy.

**Comment by alsegno** [comment]
Boris did you start looking at this?

**Comment by dreamlayers** [comment]
Cron job is running nightly at 22:00 CEST creating just an x86_64 VirtualBox Vagrant .box file. 

The script which does this is in the gitlab project.

Documentation is in the home directory of the user created for the builds. Will move it to the wiki.

**Comment by dreamlayers** [comment]
Documentation is now at automated-build-system in the private wiki.

**Comment by alsegno** [comment]
This looks great, almost ready to close.

Did we resolve yet whether/how we are going to do the nightly ARM image builds? should that go in another issue, and we can close this one?

n.

**Comment by mgax** [comment]
Let's use this issue, because we're considering the odroid c2 as our current supported ARM target, so we're not done here until that's built nightly. I'm updating the description with a checklist.

**Comment by dreamlayers** [comment]
On Slack I got the impression that we decided to do nightly ARM builds on the hetzner server, and that has been set up. The aarch64 build happens after the x86_64, and there are separate log files. I've updated the documentation regarding this.

**Comment by dreamlayers** [comment]
I've installed monit and kind of set it up with
```
check device root with path /
    if SPACE usage > 80% then alert
```
Though I'm not sure if the server is set up to send e-mail or who the e-mail should be sent to. This may be of interest: https://peteris.rocks/blog/monit-configuration-with-slack/

**Comment by mgax** [comment]
> Though I'm not sure if the server is set up to send e-mail or who the e-mail should be sent to.

I've configured the server to send email as `hetzner.liquidinvestigations.org`. Monit currently sends emails to my personal address; feel free to add your own in `/etc/monit/conf.d/alert`.

**Comment by alsegno** [comment]
can we move the nightlies into images/nightly/, and move those 'minimal' images into images/minimal/ or something?

then i think we can call this done.

**Comment by dreamlayers** [comment]
Okay, closing issue :)
