### ISSUE TITLE
all services should start on machine start

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#34]
currently none of our services start when the machine does. This means there's a manual step between booting the image and doing anything useful. all installed services should start by default.

(sort of) related to #26

**Comment by dreamlayers** [comment]
I suppose bad things may happen on first boot if I simply remove the `autostart = false` from the supervisor conf files initially. So I'm thinking on first boot:

* Don't stop services started in the script
* Start the other services
* Edit the supervisor conf files with sed so the services autostart on subsequent boots
