### ISSUE TITLE
fix default nginx page

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#35]
this should probably redirect to liquid core

**Comment by mgax** [comment]
Auto-redirecting is dangerous. Say your liquid node is called `liquid.foo.net`, and it's connected on your LAN (i.e. you're not on its hotspot and your dns server is not controlled by the liquid node), and you type in its IP address in the browser. If the nginx gives you a redirect to `liquid.foo.bar`, that request goes to your ISP's DNS, which might even take you to a placeholder page with ads. I think it's safer if we serve a default static page with a link to the correct domain. That way, you can confirm that the connection to the liquid node works, and you can debug the DNS issue separately.

**Comment by alsegno** [comment]
Ok sounds good. Talked to Gabi, assigned to him for today.
