### ISSUE TITLE
Docker to work in Ansible

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#36]

**Comment by mgax** [comment]
Pending [this PR](https://github.com/liquidinvestigations/setup/pull/9), our Ansible setup now supports docker containers. For the "pre-existing server" use case, the docker images are set up on the server normally; for the "image chroot" use case, the images are set up outside the chroot (in the temporary kitchen vm), and copied into the chroot once they are ready. We're using the `docker.io` and `docker-compose` packages from Ubuntu Xenial so we cover both x86_64 and arm64.
