### ISSUE TITLE
Select/Deselect All Collection filter button in Hoover

### ISSUE THREAD

**Issue by germakoci** [liquidinvestigations/liquidinvestigations#43]
With more collections added to Hoover, it is taking a lot of time to Click Select or Deselect each collection, one at a time, when performing searches. 

On top of the Collection list, a button to click to Select/Deselect All would be very handy. 

A more complete solution would be that the Select/Deselect button has also a mouse over show field to Search for a specific collection name to Select/Deselect like here https://digitalnewsinitiative.com/dni-projects/ [See top left Country Filter]

**Comment by alsegno** [comment]
Is this properly scoped in the Liquid Investigations project or should this live as an issue on the Hoover project. @germakoci @mgax ??

**Comment by mgax** [comment]
Is this properly scoped in the Liquid Investigations project or should this live as an issue on the Hoover project. @germakoci ??

**Comment by germakoci** [comment]
yes, for sure, needs to be delivered with the Liquid project

**Comment by alsegno** [comment]
per discussion with @germakoci moving to q4, open, backlog

**Comment by mgax** [comment]
Fixed in https://github.com/hoover/ui/commit/43b59e4004b1c58a8c6040a6f2418b805027a5c6
