### ISSUE TITLE
Default system user (for development) to be created during system setup

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#44]
We should, when building for development, ensure that there's a default user created that can:

- sudo
- login via ssh
- login via console

I propose liquid/liquid.

**Comment by alsegno** [comment]
While we're at it we should probably disable the root/odroid user for the odroid, and any other default users for whatever other images we're making, right?

**Comment by mgax** [comment]
Yep, that should give us a nice dev experience. At some point in the future we may want to allow admins, via the liquid-core gui, to upload their ssh key, so they can ssh into the liquid user.

**Comment by gabriel-v** [comment]
PR is at https://github.com/liquidinvestigations/setup/pull/13. I'll merge it after I test it. Let's leave the dev experience for the next milestone, shall we?

**Comment by alsegno** [comment]
we shall.

**Comment by dreamlayers** [comment]
The Vagrant image has vagrant/vagrant and root/vagrant as explained at https://www.vagrantup.com/docs/boxes/base.html#quot-vagrant-quot-user . This is created during the convert image script, so it is not present in the raw images.

**Comment by gabriel-v** [comment]
I know. I won't remove any system users from the image in this PR, because it's meant to ease our pain when we manually test and debug discovery on the arm boxes.

**Comment by gabriel-v** [comment]
I merged the changes.
