### ISSUE TITLE
Config file from boot partition

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#48]
work needs to be done to identify a USB stick at first boot time to get the config file.

**Comment by alsegno** [comment]
we're de-scoping this from q2. bumping to q3, putting in backlog.

**Comment by alsegno** [comment]
I think our first iteration of this is going to pull the config file from the boot partition on the SD card. That still leaves us some work to do to get the configuration file read, parsed, and used.

**Comment by alsegno** [comment]
@gabriel-v can you confirm that this config file parsing is under the scope of #2?

**Comment by alsegno** [comment]
Confirming that this should pull config from the boot partition of the SD card first time around. We don't need it to come from the USB stick until after we can prove this.

Config file scenarios are defined here: https://github.com/liquidinvestigations/liquidinvestigations/wiki/7.-User-Scenarios

Sample config file (comprehensive) is defined here:
https://github.com/liquidinvestigations/liquidinvestigations/blob/master/sample_configs/sample_config.yml

I don't want two duplicate issues kicking around so I'm going to rename this and close #2 in favour of this one. If anyone things that's the wrong thing to do, let me know.

**Comment by alsegno** [comment]
This python library may be of some help with network config: http://docs.pyroute2.org/general.html

**Comment by alsegno** [comment]
There is code for this, which needs to be merged into master in setup repo.

**Comment by gabriel-v** [comment]
it's either this, or jumpers on the GPIO pins.
Want to enable wifi? Use a jumper from pin 7 to 39!
