### ISSUE TITLE
'Discovery' via zeroconf

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#5]
Nodes to support discovery of other nodes via zeroconf. Note that this includes some DNS work and will likely interrelate with #2 .

Some consideration to be made for DNS in this task.

**Comment by alsegno** [comment]
http://www.dnspython.org/

**Comment by alsegno** [comment]
https://pypi.python.org/pypi/easyzone

**Comment by alsegno** [comment]
@gabriel-v produced these test-related docs. 

https://github.com/liquidinvestigations/docs/blob/docs-for-zeroconf/tests/TestingZeroconf.md

**Comment by gabriel-v** [comment]
Work is still in progress.

See the diffs at the following PRs that close this issue:
https://github.com/liquidinvestigations/docs/pull/1
https://github.com/liquidinvestigations/setup/pull/5
https://github.com/liquidinvestigations/core/pull/2

@alsegno Let's discuss the title and modifications on the documentation title through inline comments on the [docs pull request #1](https://github.com/liquidinvestigations/docs/pull/1). I think it's easier to communicate that way.

**Comment by alsegno** [comment]
Today we ran into a small problem regarding the behaviour of zeroconf when nodes can route to other nodes via multiple interfaces.

This needs to be resolved before we can close this issue.

**Comment by gabriel-v** [comment]
I think we can finally close this after a code review & cleanup.
https://github.com/liquidinvestigations/core/pull/3
https://github.com/liquidinvestigations/setup/pull/10
liquidinvestigations/docs#1
https://github.com/liquidinvestigations/discover

**Comment by alsegno** [comment]
Code review was done today. A few cleanup tasks still to do:

- UI stuff (move to main page, get rid of debug stuff)
- double-check that nodes are removed properly when devices drop off

Once those are complete we will test in a virtual environment again (Vagrant), then move on to testing with physical devices. Great work!

**Comment by gabriel-v** [comment]
The implementation is finished. Remaining work: revising documentation under liquidinvestigations/docs#1 with latest changes.

**Comment by alsegno** [comment]
Documentation to be completed today then this issue closed.

**Comment by gabriel-v** [comment]
The documentation is at https://github.com/liquidinvestigations/docs/pull/1.
@alsegno please review, complete and merge the PR.

**Comment by alsegno** [comment]
@gabriel-v i made some changes to the readme. i have a couple other comments that you can resolve, then you can merge and we can be done with it. hurrah!

**Comment by alsegno** [comment]
@gabriel-v did you split the test README file into two yet? I bet you can use 'head' to do it and then just change the two titles.
