### ISSUE TITLE
reconfiguring via `/boot/config.yml` file

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/liquidinvestigations#53]
[This image](http://liquidinvestigations.com/images/q2-exit/) has an implementation of reconfiguring via the `/boot/config.yml` file.

The code for that to happen is in the image itself, but not on any code repository.
We will need to move that into the setup repo.

**Comment by alsegno** [comment]
This is part of #48

**Comment by alsegno** [comment]
This is a duplicate of #48 :)
