### ISSUE TITLE
Admin UI

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#57]
catch-all issue for admin UI work

**Comment by alsegno** [comment]
see https://workflowy.com/s/B__W.BFiX4jDsdi

**Comment by alsegno** [comment]
We made some really good progress this weekend. I met with the guys from pinkfox.ro and have started initial discussions refining the requirements.

Once we've nailed down the requirements, they will (most likely) make a formal commitment and then we can start work!

Fingers crossed.

**Comment by alsegno** [comment]
Once the we finally nail down these requirements I'll turn them into a wiki page and get them into liquidinvestigations/liquidinvestigations on github. WIP here:

https://docs.google.com/document/d/1LCL-4z7_IMhr2hZj46R0LCRrAmhWHIGN3736hwEqm9M/edit?usp=sharing

**Comment by alsegno** [comment]
updated workflowy link: https://workflowy.com/s/B__W.jiyKpCpgMk

**Comment by alsegno** [comment]
documenting errors in apiblueprint documentation: https://stackoverflow.com/questions/23927424/how-to-specify-error-codes-in-apiary-documentation

the correct answer here is correct.

**Comment by gabriel-v** [comment]
Still needs:
- button to show / change domain
- VPN management
- proper handling of `network.lan.eth` boolean flag
