### ISSUE TITLE
x86 nightly build broken

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#59]
I've tried both the vagrant box and the .img, and I run into the same problem.

I use the vagrant box as-is with a dead-simple Vagrantfile. It hangs on boot.

With the .img I have tried converting to both .vdi and .vmdk and they hang on boot when I try to boot the image in virtualbox.

The culprit seems to be bad geometry on the image:

'block count x exceeds size y of device'

This is an urgent issue. Assigning to Alex, Gabi, Boris to see if any of them have a bit of time to review what I've done.

**Comment by alsegno** [comment]
If you know you're not going to work on this issue please remove yourself as an assignee.

**Comment by dreamlayers** [comment]
From `fdisk`, this is obviously wrong, as if the partition has not been resized.
```
Device                      Boot Start     End Sectors  Size Id Type
liquid-20170822-x86_64.img1 *     2048 4610047 4608000  2.2G 83 Linux
```

**Comment by dreamlayers** [comment]
The partition resizing issue should be fixed in https://github.com/liquidinvestigations/setup/commit/8dac2b909a7b4b53a06585f4789b4aed20d9e0be

**Comment by alsegno** [comment]
@all how did this end up in master without anyone noticing that it broke all our nightly builds?

**Comment by alsegno** [comment]
ok, this is fixed and i verified it.

**Comment by gabriel-v** [comment]
@alsegno You know how that happend. The python port of those scripts wasn't tested. We could
- require 1 or 2 reviews before merging into master
- set up CI (jenkins?) that must pass before we merge into master

Jenkins might be nice, because we can set up slave machines on different architectures that would build our images.

**Comment by alsegno** [comment]
A simple manual check (does it boot?) before merging would have caught this one, but yes, a CI system would be ideal. Maybe this week.

**Comment by mgax** [comment]
That's on me, I was sure I'd tested the code, but apparently it slipped. Sorry!
