### ISSUE TITLE
no xu4 nightly builds are being produced

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#61]

**Comment by dreamlayers** [comment]
`TASK [hoover : Run hoover initial setup]` fails because `/usr/bin/env: 'node': No such file or directory`.

**Comment by gabriel-v** [comment]
A first issue is that we're running a `aarch64` VM to produce a `armv7l` image for the XU4. The ansible task for node uses the VM's architecture with `ansible_arachitecture`, not our intended target architecture, as is seen [here](https://github.com/liquidinvestigations/setup/blob/master/ansible/roles/node6/tasks/main.yml#L42).

So I think we either should make buildbot run a `armv7l` VM for building the images, or we could add another flag to `setup` that sets the target architecture.

**Comment by alsegno** [comment]
@gabriel-v What's the effort involved for each?

**Comment by gabriel-v** [comment]
I'd go with making the buildbot create an `armv7` vm, to avoid any similar issues in the future.
We'd need to plug in the `armv7l` version of Ubuntu Cloud for the VM and find a suitable BIOS image. I estimate a day or two of my time, because I didn't work on buildbot or with the different qemu binaries that much.

**Comment by alsegno** [comment]
Does this help us build for rock64 as well?

**Comment by gabriel-v** [comment]
No. The rock64 has the same CPU as the c2.

**Comment by mgax** [comment]
If this is just a hoover issue, we can switch to docker hoover. We're using armv7 docker images for all arm targets, so node will just work.

**Comment by gabriel-v** [comment]
unsupported.
