### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#68]
Set up Jenkins + some sanity checks.

**Comment by gabriel-v** [comment]
We have Jenkins set up at https://88.99.150.33:8443/blue. Will follow up with an actual domain name.

I still have to write a jenkins stage that boots the resulted image with kitchen, waits for it to finish the first boot process, then archives the resulting log files for that boot process (and/or marks the build as failed/succeeded)

**Comment by gabriel-v** [comment]
Done.
