### ISSUE TITLE
Create demo movie for Google

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#7]
As done last quarter. This will use the demo server created in #6 .
Some feedback:
Writing needs to be a bit more visible (white letters are hard to see)
There should be longer breaks between the sequences (so that non tech people can also follow better)
Introduction slide (like an executive summary: i.e. this demo will show xxx users logging with credentials provided by the LI engineers and log into the various apps like: chat, annotation, search, wiki) - hosted on our internal server).

**Comment by gabriel-v** [comment]
Done. Will be uploaded shortly on [this channel](https://www.youtube.com/channel/UCm0BWF4LhS7FF12HllwWXLw).
