### ISSUE TITLE
Shared users/SSO for all applications

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#75]
Shared users (minimally) or SSO (via OAuth) to be implemented for all bundled applications.

**Comment by gabriel-v** [comment]
Davros and Hoover will be set up with oauth when https://github.com/liquidinvestigations/setup/pull/25 is merged.

Hypothesis and dokuwiki have shared users working.

Matrix shared users need additional cleanup as per https://github.com/liquidinvestigations/liquidinvestigations/issues/84.

**Comment by germakoci** [comment]
what about the integration of either Etherpad, or Hackmd into the bundle, including SSO ?

or maybe these guys ( https://github.com/xwiki-labs/cryptpad ) who seem to have a mix of both and more

**Comment by mgax** [comment]
By the way, SSO is for Q4. But we do need shared users now.

**Comment by gabriel-v** [comment]
We do have shared users working on the current master branch.
