### ISSUE TITLE
Reconfigure a live system via ansible

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/liquidinvestigations#80]
Ansible has two relevant features: [tags](https://docs.ansible.com/ansible/latest/playbooks_tags.html) and [registered variables](https://docs.ansible.com/ansible/latest/playbooks_variables.html#registered-variables).

## [Tags](https://docs.ansible.com/ansible/latest/playbooks_tags.html) 

Ansible tags let us only run tasks that are tagged with specific tags. Instead of running `ansible-playbook server.yml` once, we'll run it like `ansible-playbook server.yml --tags "tag1,tag2"`.
We would use tags like

- `image` for all the tasks that need to run at image provisioning time
- `configuration` for all the tasks that handle configuration

We could also migrate the first boot process to ansible tasks having the tag as `first-boot`.

## [Registered variables](https://docs.ansible.com/ansible/latest/playbooks_variables.html#registered-variables)

We would register, for example, all `nginx` template tasks with the `nginx` variable. We would need another role that runs last, named `restart-services`, that will run `service nginx restart` when `nginx.changed` is true.

This would happen for all services that need restarting after reconfiguration.

If there are multiple tasks registered with the same variable, ansible will produce an array with the results, but will also provide a `.changed` boolean that is set if any of the tasks have changed something on the target system.

## The research

How will we handle networking? Does the model of "try to change some files, then run some commands if they have changed" work with the networking config? What about openVPN?

**Comment by gabriel-v** [comment]
Also: `notify`

**Comment by gabriel-v** [comment]
This should also get notifications from the API endpoints from liquid-core.

**Comment by mgax** [comment]
Works goddamn it.
