### ISSUE TITLE
Server Maintenance

### ISSUE THREAD

**Issue by Luthieneye** [liquidinvestigations/liquidinvestigations#9]
Hetzner server: Sentre, Liquidinvestigations.org - Wordpress + SAAS platform

CRJI server

**Comment by Luthieneye** [comment]
Hetzner server: Sentre,  Liquidinvestigations.org - Wordpress + SAAS platform

CRJI server

**Comment by alsegno** [comment]
@gabriel-v do you have any documentation on these tasks?

**Comment by alsegno** [comment]
@gabriel-v since this is an ongoing task, I don't think it deserves a GitHub issue -- better to create a documentation task, or just know that there are docs somewhere, then we can close this?

What do you think?

**Comment by mgax** [comment]
Yeah we could use a wikipage describing our internal infrastructure. I think sentre's wiki is a good home for that page, since we'd probably want to keep it private.

**Comment by alsegno** [comment]
@mrc-toader to work with gabriel to get everything captured in a wiki page, take on ongoing maintenance.

Once the wiki page is complete, this issue should be updated and closed.

**Comment by alsegno** [comment]
question @mgax should this live alongside the nightly build docs (ie in a sentre gitlab project?)

**Comment by mgax** [comment]
> question @mgax should this live alongside the nightly build docs (ie in a sentre gitlab project?)

Yep, that makes sense.

**Comment by alsegno** [comment]
Proposal -- we need a single resource who can handle 'regular' admin/server maintenance tasks. we should create a 'maintenance window' wherein these tasks happen. *every* task that is done as part of this effort should be documented in the sentre gitlab.

I want to take this issue and move it to our internal gitlab as we should not be discussing internal server maintenance in a public forum.  Closing.
