### ISSUE TITLE
Remove matrix identity servers from config

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/liquidinvestigations#93]
There are some worrying segments of config variables in the `homeserver.yaml` file:

    trusted_third_party_id_servers:
         - matrix.org
         - vector.im
         - riot.im 

    perspectives:
       servers:
         "matrix.org":
           verify_keys:
             "ed25519:auto":
               key: "Noi6WqcDj0QmPxCNQqgezwTlBKrfqehY1u2FyWP9uYw"

We will need to set up our own id server [as is explained here](https://github.com/matrix-org/synapse#identity-servers)

**Comment by alsegno** [comment]
I was going to mention sydent, which is linked in the above explanation, but this caught my eye instead:

> "To reiterate: the Identity server will only be used if you choose to associate an email address with your account, or send an invite to another user via their email address."

Does this mean there is a chance that we can just not bother using *any* identity server?

**Comment by gabriel-v** [comment]
Then we kill them all

**Comment by alsegno** [comment]
Kill all what, exactly?

**Comment by mgax** [comment]
What @gabriel-v means is he wants to kill lines [here](https://github.com/liquidinvestigations/setup/blob/master/ansible/roles/matrix/templates/homeserver.yaml#L199-L201) and [here](https://github.com/liquidinvestigations/setup/blob/master/ansible/roles/matrix/templates/homeserver.yaml#L253-L256) so our node doesn't federate with anything.

**Comment by alsegno** [comment]
Very good. Fingers crossed this solves our problem, at least until we're ready for a feature issue that adds matrix federation or something.

**Comment by gabriel-v** [comment]
Seems these could be removed without problems.
