### ISSUE TITLE
Use dockerized hoover

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#94]

**Comment by mgax** [comment]
We're most of the way there. Dockerized hoover works on x64 with no problems, there's a pull request (https://github.com/liquidinvestigations/setup/pull/47).

For ARM, I made special docker images based on alpine, with some tweaks. They are in a new repo, [docker-arm](https://github.com/liquidinvestigations/docker-arm), that will contain scripts to build all our custom docker images. (https://github.com/liquidinvestigations/docker-arm/pull/1). The hoover images work, but their dependencies (postgres, elasticsearch, tika) have some issues that I'm working to fix.

In the mean time I made some improvements to buildbot (https://github.com/liquidinvestigations/buildbot/pull/8) to make it possible to run multiple VMs from the same buildbot folder.

**Comment by gabriel-v** [comment]
will close after alex completes manual testing

**Comment by mgax** [comment]
I'm running into issues with oauth: `hoover-search` needs to make http requests to `liquid-core`, to get an authentication token. Since `hoover-search` runs inside a docker container, its `/etc/resolv_conf` is different from the host's, and it doesn't point to our dnsmasq. There are docker flags that might help fix the issue.

So, in order to merge the "hoover docker" feature, there is non-trivial work to be done. As far as I can tell, we don't have a hard requirement to ship it, so let's postpone it to Q4. @gabriel-v, @alsegno, what do you think?

**Comment by mgax** [comment]
Nope.
