### ISSUE TITLE
Create vagrant boxes for the libvirt provider

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/liquidinvestigations#99]
[This plugin](https://github.com/vagrant-libvirt/vagrant-libvirt) integrates libvirt as a backend for vagrant.

Implementing this will let us use more powerful linux boxes for development.

To make it work with our images, we would need to obtain a `qcow2` image and use [this script](https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/tools/create_box.sh) to create the box. We will also need to use the provisioning that is already being done for the Virtualbox boxes we're already publishing.

**Comment by alsegno** [comment]
```
jpziller@hetzner:~/Repo/liquid-work$ vagrant plugin install libvirt
Installing the 'libvirt' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies ffi (~> 0.6.3) and ffi (= 1.9.18)
  Activated ffi-1.9.18
  which does not match conflicting dependency (~> 0.6.3)

  Conflicting dependency chains:
    ffi (= 1.9.18), 1.9.18 activated

  versus:
    libvirt (> 0), 0.1.0 activated, depends on
    ffi (~> 0.6.3)
```

**Comment by alsegno** [comment]
@gabriel-v did you make this work?

**Comment by alsegno** [comment]
my bad -- it should have been 

```
vagrant plugin install vagrant-libvirt
```

**Comment by alsegno** [comment]
Now I get this:
```
Error while activating network: Call to virNetworkCreate failed: error creating bridge interface virbr1: File exists.
```

**Comment by alsegno** [comment]
I had to edit the /etc/libvirt/qemu/networks/vagrant-libvirt.xml and remove the reference to the (already existing) bridge network there. This seems to have solved *that* error.

(I'm not sure if there's a way to override this systemwide setting in the Vagrantfile.)

**Comment by alsegno** [comment]
I also had to edit the systemwide libvirt configuration for the dhcp private network. at this point it just hangs forever waiting for the domain to get an IP address.

**Comment by gabriel-v** [comment]
@alsegno I didn't get past the first `error creating bridge interface virbr1: File exists.`

Retask this to you if you feel like going on with it

**Comment by mgax** [comment]
@alsegno and @gabriel-v say this is a lost cause, and it makes no sense to me.
